### PR TITLE
Monitor Plan Import Active Connections

### LINKED ISSUE #6901: Monitor Plan Import Active Connections
The MP for TEST74 failed on import during the last regression test due to a connection timeout.  While trying to diagnose the issue, I noticed that the MP import for this configuration consumes almost every connection in the pool (currently set at 60).  Inspecting pg_stat_activity during the import shows many duplicate queries against camdecmpsmd.vw_defaults_master_data_relationships for data that will not change.  It appears that these queries are being executed by monitor-default.dto when it validates the codes using @IsInDbValues decorator.

Here's an example of the queries during an import.  

[results.csv](https://github.com/user-attachments/files/22050479/results.csv)

Note that these results were generated by taking snapshots of pg_stat_activity every 5 seconds during an import.  This is the query that was used:

```sql
select CURRENT_TIMESTAMP,
       pid,
       application_name,
       state,
       CURRENT_TIMESTAMP - query_start AS query_duration,
       query_id,
       query
from pg_stat_activity
where application_name = 'monitor-plan-api'
order by query;
```

Ideally these results should be cached.  There may be a way to do this just by modifying the validator code.  Here's an example (note: Copilot came up with this solution):

```typescript
import { Injectable } from '@nestjs/common';
import {
  registerDecorator,
  ValidationOptions,
  ValidatorConstraint,
  ValidatorConstraintInterface,
  ValidationArguments,
} from 'class-validator';
import { isInactiveRecord } from '../../utilities/is-inactive-record';
import { DataSource } from 'typeorm';
import * as crypto from 'crypto';

interface ignoreOptions {
  ignoreEmptyIfInactive?: boolean;
}

// Simple in-memory cache
const dbValueCache: Record<string, any[]> = {};

function hashSql(sql: string): string {
  return crypto.createHash('sha256').update(sql).digest('hex');
}

@ValidatorConstraint({ async: true })
@Injectable()
export class IsInDbValuesConstraint implements ValidatorConstraintInterface {
  constructor(private readonly connection: DataSource) {}

  async validate(value: string, args: ValidationArguments) {
    const { sql, options } = args.constraints[0];
    if (options && options.ignoreEmptyIfInactive) {
      const beginDate = args.object['beginDate'];
      const endDate = args.object['endDate'];
      if (!value && isInactiveRecord(beginDate, endDate)) {
        return true;
      }
    }

    const cacheKey = hashSql(sql);

    if (!dbValueCache[cacheKey]) {
      const data = await this.connection.query(sql);
      dbValueCache[cacheKey] = data.map(entry => entry.value);
    }

    return dbValueCache[cacheKey].includes(value);
  }
}

export function IsInDbValues(
  sql: string,
  validationOptions?: ValidationOptions,
  options?: ignoreOptions
) {
  return function (object: Object, propertyName: string) {
    registerDecorator({
      target: object.constructor,
      propertyName: propertyName,
      options: validationOptions,
      constraints: [{ sql, options }],
      validator: IsInDbValuesConstraint,
    });
  };
}
```
There may be issues with a cache like this consuming memory but an eviction policy could be implemented to mitigate.  There may be a library that already does this. 

**Other Research Notes**
Most of the DTO validations that use one of the vw_*****_master_data_relationships views do not need to use a view.   These changes should be made first to determine if caching is necessary in the short-term.

The following DTO validations should use the camdecmpsmd table that contains the valid values for the field:
 - unit_fuel.dto
   - fuel_type_cd - camdecmpsmd.fuel_type_code
   - fuel_indicator_cd - camdecmpsmd.fuel_indicator_code
   - dem_gcv - camdecmpsmd.dem_method_code where dem_parameter = 'GCV'
   - dem_so2 - camdecmpsmd.dem_method_code where dem_parameter = 'SULFUR'
 - monitor_method.dto
   - method_code - camdecmpsmd.method_code
   - substitute_data_code - camdecmpsmd.substitute_data_code
   - bypass_approach_code - camdecmpsmd.bypass_approach_code
 - lee_qualification.dto
   - qual_lee_test_type_cd - camdecmpsmd.qual_lee_test_type_code
 - monitor-default.dto 
   - purpose_code - camdecmpsmd.default_purpose_code
   - operating_condition_code - camdecmpsmd.operating_condition_code
   - source_code - camdecmpsmd.default_source_code
 - monitor-load.dto 
   - normal_level - camdecmpsmd.operating_level_code
   - second_level - camdecmpsmd.operating_level_code
 - monitor-span.dto
   - span_scale_code - camdecmpsmd.span_scale_code
   - span_method_code - camdecmpsmd.span_method_code

The following DTO validations should use a new DTO-specific view (querying camdecmpsmd.cross_check_catalog and camdecmpsmd.cross_check_catalog_value) that only selects the information for the field required to validate:
 - monitor_method.dto
   - parameter_code -new view camdecmpsmd.vw_dto_parameter_code where record_type = 'METHOD'
 - lee_qualification.dto
   - parameter_code - new view camdecmpsmd.vw_dto_parameter_code where record_type = 'QUALLEE' 
   - unit_of_standard_code - new view camdecmpsmd.vw_dto_unit_of_measure_code where record_type = 'QUALLEE'
 - monitor-default.dto
   - parameter_code - new view camdecmpsmd.vw_dto_parameter_code where record_type = 'DEFAULT' 
   - unit_of_measure_code - new view camdecmpsmd.vw_dto_unit_of_measure_code where record_type = 'DEFAULT' 
 - monitor-load.dto 
    - unit_of_measure_code - new view camdecmpsmd.vw_dto_unit_of_measure_code where record_type = 'LOAD' 
 - monitor-span.dto 
   - unit_of_measure_code - new view camdecmpsmd.vw_dto_unit_of_measure_code where record_type = 'SPAN' 
 - system-fuel-flow.dto 
   - unit_of_measure_code -new view camdecmpsmd.vw_dto_unit_of_measure_code where record_type = 'SYSFUEL'

### PR DESCRIPTION
**Pull request by Jhernandez29**
ticket:
https://github.com/US-EPA-CAMD/easey-monitor-plan-api/pull/798

changes:
Created camdecmpsmd.vw_dto_parameter_code and camdecmpsmd.vw_dto_unit_of_measure_code that only selects the information for the fields required to validate.

Updated PR with new code changes according to review.

### CODE REVIEW

File: camdecmpsmd/views/vw_dto_parameter_code.sql
Comment (djw4erg) [inline camdecmpsmd/views/vw_dto_parameter_code.sql:1]: ### Issues

1. Instead of using the exact same query three time (except for the Value2 value) UNIONed together, use the query once with an IN parameter on containing the three values.
2. The query currently does not need to use Distinct for two reasons.
   1. The current cross check values for generic crosscheck 'Parameter to Category' do not contain duplicates.
   2. #6931 was created to eliminate duplicates and the possibility of duplicates in the camdecmpsmd CROSS_CHECK_CATALOG_VALUE table.
      - CROSS_CHK_CATALOG_ID, VALUE1, VALUE2, and VALUE3 should for a unique key for CROSS_CHECK_CATALOG_VALUE.

### Example
```
select  ccv.value1 as parameter_code,
        ccv.value2 as record_type
  from  camdecmpsmd.CROSS_CHECK_CATALOG ccc
        join camdecmpsmd.CROSS_CHECK_CATALOG_VALUE ccv using ( cross_chk_catalog_id )
 where  ccc.cross_chk_catalog_name = 'Parameter to Category'
   and  ccv.value2 in ( 'DEFAULT', 'METHOD', 'QUALLEE' );
```

File: camdecmpsmd/views/vw_dto_unit_of_measure_code.sql
Comment (djw4erg) [inline camdecmpsmd/views/vw_dto_unit_of_measure_code.sql:1]: ### Issue

When a DTO uses this view to check a specific value type ( 'DEFAULT', 'LOAD', 'QUALLEE'. 'SPAN', and 'SYSFUEL') the rows are produced for all five value types.  Unlike VW_DTO_PARAMETER_CODE two of the subqueries in VW_DTO_UNIT_OF_MEASURE_CODE completely differ from the other three queries.  This prevents combining them into a single query using an IN operator.

1. As a result I believe that the instead of one view, the solution for UOM is five views, one for each value type.
2. This will require changes on top of the changes already made to the EASEY-MONITOR-PLAN-API.

### Examples

#### DEFAULT View (VW_DTO_UOM_CODE_FOR_DEFAULT) Body Example

- Distinct is needed here because duplicates are inherent because some UOM are used by multiple component types that require spans.
- Each of the default parameters in the 'Parameter to Category' crosscheck contain UOM in the 'Parameter Code to Units of Measure Code for Defaults' crosscheck.

```
select  distinct
        uom.unit_of_measure_code
  from  ( 
            select  ccv.value1 as parameter_code
              from  camdecmpsmd.CROSS_CHECK_CATALOG ccc
                    join camdecmpsmd.CROSS_CHECK_CATALOG_VALUE ccv using ( cross_chk_catalog_id )
             where  ccc.cross_chk_catalog_name = 'Parameter to Category'
               and  ccv.value2 = 'DEFAULT'
        ) def
        join 
        (
            select  ccv.value1 as parameter_code,
                    ccv.value2 as unit_of_measure_code
              from  camdecmpsmd.CROSS_CHECK_CATALOG ccc
                    join camdecmpsmd.CROSS_CHECK_CATALOG_VALUE ccv using ( cross_chk_catalog_id )
             where  ccc.cross_chk_catalog_name = 'Parameter Code to Units of Measure Code for Defaults'
        ) uom
          on uom.parameter_code = def.parameter_code;
```

#### LOAD View (VW_DTO_UOM_CODE_FOR_LOAD) Body Example

- Distinct is not needed because the underlying generic crosscheck should not have duplicates and ticket #6931 will add a unique constraint to ensure the uniqueness of CROSS_CHECK_CATALOG_VALUE entries.

```
select  ccv.value1 as parameter_code
  from  camdecmpsmd.CROSS_CHECK_CATALOG ccc
        join camdecmpsmd.CROSS_CHECK_CATALOG_VALUE ccv using ( cross_chk_catalog_id )
 where  ccc.cross_chk_catalog_name = 'Units of Measure to Category'
   and  ccv.value2 = 'LOAD';
```

#### QUALLEE View (VW_DTO_UOM_CODE_FOR_QUALLEE) Body Example

- Distinct is not needed because the underlying generic crosscheck should not have duplicates and ticket #6931 will add a unique constraint to ensure the uniqueness of CROSS_CHECK_CATALOG_VALUE entries.

```
select  ccv.value1 as parameter_code
  from  camdecmpsmd.CROSS_CHECK_CATALOG ccc
        join camdecmpsmd.CROSS_CHECK_CATALOG_VALUE ccv using ( cross_chk_catalog_id )
 where  ccc.cross_chk_catalog_name = 'Units of Measure to Category'
   and  ccv.value2 = 'QUALLEE';
```

#### SPAN View (VW_DTO_UOM_CODE_FOR_SPAN) Body Example

- Distinct is needed here because duplicates are inherent because some UOM are used by multiple parameters.
- Each of the component types in the 'Component Type to Category' crosscheck contain UOM in the 'Component Type Code to Units of Measure for Span' crosscheck.

```
select  distinct
        uom.unit_of_measure_code
  from  ( 
            select  ccv.value1 as component_type_code
              from  camdecmpsmd.CROSS_CHECK_CATALOG ccc
                    join camdecmpsmd.CROSS_CHECK_CATALOG_VALUE ccv using ( cross_chk_catalog_id )
             where  ccc.cross_chk_catalog_name = 'Component Type to Category'
               and  ccv.value2 = 'SPAN'
        ) spn
        join 
        (
            select  ccv.value1 as component_type_code,
                    ccv.value2 as unit_of_measure_code
              from  camdecmpsmd.CROSS_CHECK_CATALOG ccc
                    join camdecmpsmd.CROSS_CHECK_CATALOG_VALUE ccv using ( cross_chk_catalog_id )
             where  ccc.cross_chk_catalog_name = 'Component Type Code to Units of Measure for Span'
        ) uom
          on uom.component_type_code = spn.component_type_code;
```

#### SYSFUEL View (VW_DTO_UOM_CODE_FOR_SYSFUEL) Body Example

- Distinct is not needed because the underlying generic crosscheck should not have duplicates and ticket #6931 will add a unique constraint to ensure the uniqueness of CROSS_CHECK_CATALOG_VALUE entries.

```
select  ccv.value1 as parameter_code
  from  camdecmpsmd.CROSS_CHECK_CATALOG ccc
        join camdecmpsmd.CROSS_CHECK_CATALOG_VALUE ccv using ( cross_chk_catalog_id )
 where  ccc.cross_chk_catalog_name = 'Units of Measure to Category'
   and  ccv.value2 = 'SYSFUEL';
```

**Review by djw4erg — CHANGES_REQUESTED** [review]

File: camdecmpsmd/views/vw_dto_parameter_code.sql
Comment (Jhernandez29) [reply camdecmpsmd/views/vw_dto_parameter_code.sql:1]: Updated sql file.

File: camdecmpsmd/views/vw_dto_unit_of_measure_code.sql
Comment (Jhernandez29) [reply camdecmpsmd/views/vw_dto_unit_of_measure_code.sql:1]: Added five UOM views.

File: camdecmpsmd/views/vw_dto_uom_code_for_default.sql [hunk 1]
```diff
@@ -0,0 +1,21 @@
+CREATE OR REPLACE VIEW camdecmpsmd.vw_uom_code_for_default AS
+select  distinct
+        uom.unit_of_measure_code,
+        def.value2 as record_type
```
Comment (djw4erg) [inline camdecmpsmd/views/vw_dto_uom_code_for_default.sql]: RECORD_TYPE is not needed because the query limits the record type to 'DEFAULT' and the view name indicates that it is for Defaults.

File: camdecmpsmd/views/vw_dto_uom_code_for_load.sql [hunk 2]
```diff
@@ -0,0 +1,7 @@
+CREATE OR REPLACE VIEW camdecmpsmd.vw_uom_code_for_load AS
+select  ccv.value1 as unit_of_measure_code,
+		    ccv.value2 as record_type
```
Comment (djw4erg) [inline camdecmpsmd/views/vw_dto_uom_code_for_load.sql]: RECORD_TYPE is not needed because the query limits the record type to 'LOAD' and the view name indicates that it is for Loads.

File: camdecmpsmd/views/vw_dto_uom_code_for_quallee.sql [hunk 3]
```diff
@@ -0,0 +1,7 @@
+CREATE OR REPLACE VIEW camdecmpsmd.vw_uom_code_for_quallee AS
+select  ccv.value1 as unit_of_standard_code,
+		    ccv.value2 as record_type
```
Comment (djw4erg) [inline camdecmpsmd/views/vw_dto_uom_code_for_quallee.sql]: RECORD_TYPE is not needed because the query limits the record type to 'QUALLEE' and the view name indicates that it is for Qualification LEEs.

File: camdecmpsmd/views/vw_dto_uom_code_for_span.sql [hunk 4]
```diff
@@ -0,0 +1,21 @@
+CREATE OR REPLACE VIEW camdecmpsmd.vw_uom_code_for_span AS
+select  distinct
+        uom.unit_of_measure_code,
+        spn.value2 as record_type
```
Comment (djw4erg) [inline camdecmpsmd/views/vw_dto_uom_code_for_span.sql]: RECORD_TYPE is not needed because the query limits the record type to 'SPAN' and the view name indicates that it is for Spans.

File: camdecmpsmd/views/vw_dto_uom_code_for_sysfuel.sql [hunk 5]
```diff
@@ -0,0 +1,7 @@
+CREATE OR REPLACE VIEW camdecmpsmd.vw_uom_code_for_sysfuel AS
+select  ccv.value1 as unit_of_measure_code,
+		    ccv.value2 as record_type
```
Comment (djw4erg) [inline camdecmpsmd/views/vw_dto_uom_code_for_sysfuel.sql]: RECORD_TYPE is not needed because the query limits the record type to 'SYSFUEL' and the view name indicates that it is for System Fuels.

**Review by djw4erg — CHANGES_REQUESTED** [review]

File: camdecmpsmd/views/vw_dto_uom_code_for_default.sql (hunk 1 above)
Comment (Jhernandez29) [reply camdecmpsmd/views/vw_dto_uom_code_for_default.sql]: Resolved with last commit

File: camdecmpsmd/views/vw_dto_uom_code_for_load.sql (hunk 2 above)
Comment (Jhernandez29) [reply camdecmpsmd/views/vw_dto_uom_code_for_load.sql]: Resolved with last commit

File: camdecmpsmd/views/vw_dto_uom_code_for_quallee.sql (hunk 3 above)
Comment (Jhernandez29) [reply camdecmpsmd/views/vw_dto_uom_code_for_quallee.sql]: Resolved with last commit

File: camdecmpsmd/views/vw_dto_uom_code_for_span.sql (hunk 4 above)
Comment (Jhernandez29) [reply camdecmpsmd/views/vw_dto_uom_code_for_span.sql]: Resolved with last commit

File: camdecmpsmd/views/vw_dto_uom_code_for_sysfuel.sql (hunk 5 above)
Comment (Jhernandez29) [reply camdecmpsmd/views/vw_dto_uom_code_for_sysfuel.sql]: Resolved with last commit

**Review by djw4erg — APPROVED** [review]

File: camdecmpsmd/views/vw_dto_uom_code_for_default.sql [hunk 6]
```diff
@@ -0,0 +1,19 @@
+CREATE OR REPLACE VIEW camdecmpsmd.vw_uom_code_for_default AS
```
Comment (djw4erg) [inline camdecmpsmd/views/vw_dto_uom_code_for_default.sql]: Include DTO in the actual view name.

File: camdecmpsmd/views/vw_dto_uom_code_for_load.sql [hunk 7]
```diff
@@ -0,0 +1,6 @@
+CREATE OR REPLACE VIEW camdecmpsmd.vw_uom_code_for_load AS
```
Comment (djw4erg) [inline camdecmpsmd/views/vw_dto_uom_code_for_load.sql]: Include DTO in the actual view name.

File: camdecmpsmd/views/vw_dto_uom_code_for_quallee.sql [hunk 8]
```diff
@@ -0,0 +1,6 @@
+CREATE OR REPLACE VIEW camdecmpsmd.vw_uom_code_for_quallee AS
```
Comment (djw4erg) [inline camdecmpsmd/views/vw_dto_uom_code_for_quallee.sql]: Include DTO in the actual view name.

File: camdecmpsmd/views/vw_dto_uom_code_for_span.sql [hunk 9]
```diff
@@ -0,0 +1,18 @@
+CREATE OR REPLACE VIEW camdecmpsmd.vw_uom_code_for_span AS
```
Comment (djw4erg) [inline camdecmpsmd/views/vw_dto_uom_code_for_span.sql]: Include DTO in the actual view name.

File: camdecmpsmd/views/vw_dto_uom_code_for_sysfuel.sql [hunk 10]
```diff
@@ -0,0 +1,6 @@
+CREATE OR REPLACE VIEW camdecmpsmd.vw_uom_code_for_sysfuel AS
```
Comment (djw4erg) [inline camdecmpsmd/views/vw_dto_uom_code_for_sysfuel.sql]: Include DTO in the actual view name.

**Review by djw4erg — CHANGES_REQUESTED** [review]

File: camdecmpsmd/views/vw_dto_uom_code_for_default.sql (hunk 6 above)
Comment (Jhernandez29) [reply camdecmpsmd/views/vw_dto_uom_code_for_default.sql]: solved in last commit

File: camdecmpsmd/views/vw_dto_uom_code_for_load.sql (hunk 7 above)
Comment (Jhernandez29) [reply camdecmpsmd/views/vw_dto_uom_code_for_load.sql]: solved in last commit

File: camdecmpsmd/views/vw_dto_uom_code_for_span.sql (hunk 9 above)
Comment (Jhernandez29) [reply camdecmpsmd/views/vw_dto_uom_code_for_span.sql]: solved in last commit

File: camdecmpsmd/views/vw_dto_uom_code_for_sysfuel.sql (hunk 10 above)
Comment (Jhernandez29) [reply camdecmpsmd/views/vw_dto_uom_code_for_sysfuel.sql]: solved in last commit

File: camdecmpsmd/views/vw_dto_uom_code_for_quallee.sql (hunk 8 above)
Comment (Jhernandez29) [reply camdecmpsmd/views/vw_dto_uom_code_for_quallee.sql]: solved in last commit

**Review by djw4erg — APPROVED** [review]
