### PR TITLE
fix/#6571 Add NO WINDOW Option in Status Filter for EM Submission Access

### LINKED ISSUE #6571: Add "No Window" option in Status Filter for Emission Submission Access
This ticket is created based on [#6079](https://github.com/orgs/US-EPA-CAMD/projects/2/views/6?filterQuery=6079&pane=issue&itemId=53268940&issue=US-EPA-CAMD%7Ceasey-ui%7C6079) 

The Status filter list in EM Submission Access needs to be updated, "No Window" option should be added to the list. 

- No Window: No EM Submission Window rows exist for the MP and reporting period combination. For ECMPS 1.0, only seen in testing environments because the Window Job would normally create the windows.

@djw4erg added examples of ECMPS 1.0 query used to populate the Create Window screen:

- Script to populate the Create Window screen: https://github.com/US-EPA-CAMD/easey-ui/issues/6079#issuecomment-2613207535
- Function fncGetEmSubmissionStatus: https://github.com/US-EPA-CAMD/easey-ui/issues/6079#issuecomment-2613226944
- Monitor Plan View: https://github.com/US-EPA-CAMD/easey-ui/issues/6079#issuecomment-2616615904

Also:
1/31/25 -- Update the logic about enabling "Apply Filter(s)" button to only when both Facility ID/Name and Reporting Period filters are filled.

### PR DESCRIPTION
**Pull request by EvanSun220**
### **Related Ticket:**
- ticket [#6571](https://github.com/orgs/US-EPA-CAMD/projects/2/views/6?filterQuery=6571&pane=issue&itemId=95423915&issue=US-EPA-CAMD%7Ceasey-ui%7C6571), as a part of [#6079](https://github.com/orgs/US-EPA-CAMD/projects/2/views/6?filterQuery=6079&pane=issue&itemId=53268940&issue=US-EPA-CAMD%7Ceasey-ui%7C6079)
### **Updates:**
- Added view camdecmps.vw_monitor_plan and function camdecmpsaux.get_em_submission_access_no_window_view to get all "NO WINDOW" status records for specific facility and reporting period.

### CODE REVIEW

File: camdecmpsaux/functions/get_em_submission_access_no_window_view.sql [hunk 1]
```diff
@@ -0,0 +1,114 @@
...
+        NULL::text                      AS severity_cd,
+        NULL::text                      AS severity_cd_description,
+        vmp.locations                   AS locations
+    FROM camdecmps.vw_monitor_plan vmp
+    JOIN (
+        SELECT 
+            mp.mon_plan_id,
+            rp.rpt_period_id,
+            CONCAT(rp.calendar_year, ' Q', rp.quarter) AS period,
+            -- originally: camdecmpsaux.get_em_submission_status(mp.mon_plan_id, rp.calendar_year, rp.quarter)
```
Comment (mark-hayward-erg) [inline camdecmpsaux/functions/get_em_submission_access_no_window_view.sql]: We need to actually call this function.  This function is what determines if the MP is expected to report for the reporting period.

This appears to be correct in the deployment version, but not in this file.

**Review by mark-hayward-erg — CHANGES_REQUESTED** [review]

**Review by mark-hayward-erg — APPROVED** [review]
