### PR TITLE
Fix/6264 update camdecmpswks.monitor plan flags when loading the workspace

### LINKED ISSUE #6264: Update CAMDECMPSWKS.MONITOR_PLAN flags when loading the workspace
All monitoring plans from CAMDECMPS.MONITOR_PLAN appear to have been copied to the same table in CAMDECMPSWKS as part of the data load process. This was noticed while testing #5895. #5895 specifically handled updating UPDATED_STATUS_FLG to N and NEEDS_EVAL_FLG to Y during a revert, but the HOURGEN-8-B issues will still exist unless a user 1.) evaluates the MP or 2.) reverts to official first.

Per 5/20/2024 ECMPS Priorities meeting, we should set UPDATED_STATUS_FLG to N and NEEDS_EVAL_FLG to Y in CAMDECMPSWKS.MONITOR_PLAN where SUBMISSION_AVAILABILITY_CD = UPDATED when the final data refresh is completed and prior to the production release. 

This can be accomplished by updating camdecmpswks.**load_monitor_plan_workspace**().  load_monitor_plan_workspace() is part of the call to camdecmpswks.**load_workspace**() in the **[easey-db-scripts]\deployments\ecmps\release-v2.0\deploy.sh** script that will be part of the data load process.

**Technical Details**
 - If SUBMISSION_AVAILABILITY_CD = UPDATED in the official monitor_plan record,
   - Set UPDATED_STATUS_FLG to N and NEEDS_EVAL_FLG to Y
 - Otherwise,
   - Set UPDATED_STATUS_FLG to Y and NEEDS_EVAL_FLG to Y 

**Acceptance Tests:**

1. Execute "call camdecmpswks.load_workspace()".
2. The query "select * from camdecmpswks.monitor_plan where submission_availability_cd = 'UPDATED' and updated_status_flg <> 'N' and needs_eval_flg <> 'Y'" should return no results.
3. Find active MP examples in official where "select * from camdecmps.monitor_plan where submission_availability_cd = 'REQUIRE' and updated_status_flg  = 'Y' and needs_eval_flg = 'Y'" returns results.
4. Run the same query from above using "camdecmpswks.monitor_plan" instead. The submission_availability_cd, updated_status_flg, and needs_eval_flg columns should match official for any example MP's.

### PR DESCRIPTION
**Pull request by ayang2017**
Script for SP saved at two location (deployments/ecmps/release-v2.0-fix/Spring19/6264/camdecmpswks, camdecmpswk/procedure)

### CODE REVIEW

File: camdecmpswks/procedures/load_monitor_plan_workspace.sql [hunk 1]
```diff
@@ -1,265 +1,269 @@
...
+    INSERT INTO camdecmpswks.monitor_plan(
+      mon_plan_id, fac_id, config_type_cd, last_updated, updated_status_flg, needs_eval_flg, chk_session_id, userid, add_date, update_date, submission_id, submission_availability_cd, begin_rpt_period_id, end_rpt_period_id, last_evaluated_date, eval_status_cd
+    )
+    SELECT
+      mp.mon_plan_id, mp.fac_id, mp.config_type_cd, mp.last_updated, mp.updated_status_flg, mp.needs_eval_flg, mp.chk_session_id, mp.userid, mp.add_date, mp.update_date, mp.submission_id, mp.submission_availability_cd, mp.begin_rpt_period_id, mp.end_rpt_period_id, mp.last_evaluated_date, coalesce(sc.eval_status_cd, 'PASS')
+    FROM camdecmps.monitor_plan mp
+    LEFT JOIN camdecmpsaux.check_session cs on cs.chk_session_id = mp.chk_session_id
+    LEFT JOIN camdecmpsmd.severity_code sc on sc.severity_cd = cs.severity_cd;
+    -- need update two flags when SUBMISSION_AVAILABILITY_CD=UPDATED
+	UPDATE camdecmpswks.monitor_plan
```
Comment (djw4erg) [inline camdecmpswks/procedures/load_monitor_plan_workspace.sql]: ### Under Technical Details in the ticket description the following is indicated:

 - If SUBMISSION_AVAILABILITY_CD = UPDATED in the official monitor_plan record,
   - Set UPDATED_STATUS_FLG to N and NEEDS_EVAL_FLG to Y
 - Otherwise,
   - Set UPDATED_STATUS_FLG to Y and NEEDS_EVAL_FLG to Y 

### Issue

1. The change only does the "then" part but does not do the else.
2. Only a suggestion, but the insert could be altered instead of adding an update.  See the example "**insert only**" change below.

#### Example Change

```
    insert
      into  camdecmpswks.monitor_plan
            (
                mon_plan_id, 
                fac_id, 
                config_type_cd, 
                last_updated, 
                updated_status_flg, 
                needs_eval_flg, 
                chk_session_id, 
                userid, 
                add_date, 
                update_date, 
                submission_id, 
                submission_availability_cd, 
                begin_rpt_period_id, 
                end_rpt_period_id, 
                last_evaluated_date, 
                eval_status_cd
            )
    select  mp.mon_plan_id, 
            mp.fac_id, 
            mp.config_type_cd, 
            mp.last_updated, 
            ( case when mp.submission_availability_cd = 'UPDATED' then 'N' else 'Y' end ) as updated_status_flg, 
            'Y' as needs_eval_flg, 
            mp.chk_session_id, 
            mp.userid, 
            mp.add_date, 
            mp.update_date, 
            mp.submission_id, 
            mp.submission_availability_cd, 
            mp.begin_rpt_period_id, 
            mp.end_rpt_period_id, 
            mp.last_evaluated_date, 
            coalesce(sc.eval_status_cd, 'PASS') as eval_status_cd
      from  camdecmps.MONITOR_PLAN mp
            left join camdecmpsaux.CHECK_SESSION cs on cs.chk_session_id = mp.chk_session_id
            left join camdecmpsmd.SEVERITY_CODE sc on sc.severity_cd = cs.severity_cd;
```

File: deployments/ecmps/release-v2.0-fix/Spring19/6264/camdecmpswks/load_monitor_plan_workspace
Comment (djw4erg) [inline deployments/ecmps/release-v2.0-fix/Spring19/6264/camdecmpswks/load_monitor_plan_workspace:1]: ## Two Naming Issues

1. The name of the file does not include the "**.sql**" extension.
2. The file is in the "**Spring19**" folder instead of the "**Sprint19**" folder.

**Review by djw4erg — CHANGES_REQUESTED** [review]

File: deployments/ecmps/release-v2.0-fix/Spring19/6264/camdecmpswks/load_monitor_plan_workspace
Comment (ayang2017) [reply deployments/ecmps/release-v2.0-fix/Spring19/6264/camdecmpswks/load_monitor_plan_workspace:1]: Updated SP and corrected naming issue.

**Review by djw4erg — CHANGES_REQUESTED** [review]
The version of the SP in the Dev DB needs to be updated.

**Comment by ayang2017** [comment]
I saved the updated SP at both location:
 --deployments/ecmps/release-v2.0-fix/Sprint19/6264/camdecmpswks, 
-- camdecmpswk/procedure

**Comment by djw4erg** [comment]
> I saved the updated SP at both location: --deployments/ecmps/release-v2.0-fix/Sprint19/6264/camdecmpswks, -- camdecmpswk/procedure

The scripts have been updated, but the **database** still has the old version of the procedure.

**Review by djw4erg — CHANGES_REQUESTED** [review]
Before looking at this in detail again, the deployment script changes should be part of this PR.

**Comment by ayang2017** [comment]
Updated SP saved at database and  Github
--deployments/ecmps/release-v2.0-fix/Sprint19/6264/camdecmpswks,
-- camdecmpswk/procedure

**Review by djw4erg — APPROVED** [review]
