### PR TITLE
fix(#6068): fixed issue of join removing non-submitted evaluations

### LINKED ISSUE #6068: Incorrect Submission Status for Emissions in Evaluate screen
An incorrect Submission Status is displayed in the Evaluate screen for Emissions for quarters with closed windows.

Import a 2023 Q2 EM file from historical and navigate to the Evaluate screen.

Submission Status indicates "Permission to Resubmit Granted" and Submission Window indicates "Closed". 

**Requirements Note**:
In ECMPS 1.0 the Submission Availability Code for emissions was added to the EMISSION_EVALUATION table and used in view VW_EM_EVAL_AND_SUBMIT to determine the submission availability.  However, for emissions the submission availability is controlled by the EM_SUBMISSION_ACCESS table and the submission availability that it contains.  The following is SQL that shows how to pull the submission availability from the potentially multiple EM_SUBMISSION_ACCESS entries for each emission report.

[VW_EM_EVAL_AND_SUBMIT.ReplacementSql.txt](https://github.com/US-EPA-CAMD/easey-ui/files/14411902/VW_EM_EVAL_AND_SUBMIT.ReplacementSql.txt)

### PR DESCRIPTION
**Pull request by maxdiebold-erg**
## Main Changes:

- Updated the `vw_em_eval_and_submit` views to include evaluations without submissions.
  - The submission codes still pull from the latest submission, but evaluations without submissions are included with empty fields for the submission data.

## Steps to Test:

1. Run the workspace query that is currently in place against the Dev database, and save or note the output.
2. Run the updated query against the Dev database (**starting with `SELECT`**), and note the output. There should be more rows in the output of the updated query, but the additional rows should have null values for `submission_availability_cd`, `submission_availability_cd_description`, `user_id`, `update_date`, and `window_status`.
3. Compare the row count of the `camdecmps.vw_em_eval_and_submit` query with the view that was in place when this issue was raised. This is the count query for the original view:
```
SELECT
    count(*)
FROM (
    SELECT
        p.oris_code,
        p.facility_name,
        d.mon_plan_id,
        d.configuration,
        esa.userid,
        esa.update_date AS update_date,
        esa.window_status AS window_status,
        rpt.period_abbreviation
    FROM
        camd.plant p
        JOIN camdecmps.monitor_plan mp USING (fac_id)
        JOIN (
            SELECT
                mon_plan_id, string_agg(unit_stack, ', ') AS configuration
            FROM (
                SELECT
                    mon_plan_id,
                    COALESCE(unitid, stack_name) AS unit_stack
                FROM
                    camdecmps.monitor_plan_location mpl
                    JOIN camdecmps.monitor_location ml USING (mon_loc_id)
                    LEFT JOIN camdecmps.stack_pipe USING (stack_pipe_id)
                    LEFT JOIN camd.unit USING (unit_id)
                ORDER BY
                    mon_plan_id, unitid, stack_name) AS d1
            GROUP BY
                mon_plan_id) AS d USING (mon_plan_id)
JOIN camdecmps.emission_evaluation ee USING (mon_plan_id)
JOIN camdecmpsmd.reporting_period rpt ON ee.rpt_period_id = rpt.rpt_period_id
    LEFT JOIN ( SELECT DISTINCT ON (esa.mon_plan_id, esa.rpt_period_id)
            esa.mon_plan_id, esa.rpt_period_id, esa.userid, COALESCE(esa.update_date, esa.add_date) AS update_date,
            esa.sub_availability_cd AS window_status
        FROM
            camdecmpsaux.em_submission_access esa
        WHERE
            esa.em_status_cd::text <> 'RECVD'::text
        ORDER BY
            esa.mon_plan_id,
            esa.rpt_period_id,
            esa.access_begin_date DESC) esa ON ee.mon_plan_id::text = esa.mon_plan_id::text
        AND ee.rpt_period_id = esa.rpt_period_id
    ORDER BY
        p.oris_code,
        configuration,
        rpt.period_abbreviation) AS foo;
```

## TODO:

- [x] Look into the UI and check if the output needs to be adjusted to account for empty submission windows. @esaber76 noted that in 1.0, if the window isn't open yet it displays something similar to "No Submission Window".

### CODE REVIEW

File: camdecmps/views/vw_em_eval_and_submit.sql [hunk 1]
```diff
@@ -16,37 +16,40 @@ SELECT
...
-            ems.rpt_period_id,
-            (
-                SELECT
-                    esa.em_sub_access_id
-                FROM (
+        rpt.period_abbreviation
+    FROM
+        camd.plant p
+        JOIN camdecmps.monitor_plan mp ON mp.fac_id = p.fac_id
+        JOIN camdecmps.emission_evaluation ee ON ee.mon_plan_id = mp.mon_plan_id
```
Comment (djw4erg) [inline camdecmps/views/vw_em_eval_and_submit.sql]: This join to EMISSION_EVALUATION is not needed since the "lst" subquery includes the same information.  Additionally the REPORTING_PERIOD will need to join to the subquery results.

**Review by djw4erg — CHANGES_REQUESTED** [review]

**Comment by maxdiebold-erg** [comment]
The UI changes that correspond to this pull request are addressed in https://github.com/US-EPA-CAMD/easey-ecmps-ui/pull/1401.

**Review by djw4erg — APPROVED** [review]
