### PR TITLE
fix/#6622-submission-list-report

### LINKED ISSUE #6622: Complete List of Submissions Report (CAT)
(continuation of #4675 )

### PR DESCRIPTION
**Pull request by Jhernandez29**
ticket
https://github.com/US-EPA-CAMD/easey-ui/issues/6622
changes
Remove DROP from scripts and move files to the right camdecmps folder.

### CODE REVIEW

File: camdecmps/functions/get_last_submission.sql [hunk 1]
```diff
@@ -1,6 +1,4 @@
-DROP FUNCTION IF EXISTS camdecmpsaux.get_last_submission_list(character varying, numeric, character varying) CASCADE;
-
-CREATE OR REPLACE FUNCTION camdecmpsaux.get_last_submission_list(
```
Comment (mark-hayward-erg) [inline camdecmps/functions/get_last_submission.sql]: The actual name of the function needs to be "get_last_submission".  The file name is correct.

File: camdecmps/views/vw_submission_list.sql [hunk 2]
```diff
@@ -29,11 +25,9 @@ select  fac.oris_code,
        sbq.submission_id,
        sbq.queued_time,
        sev.severity_cd_description as severity_level,
-       case
-          when exists
-               (
+        (SELECT
                 CASE 
-                WHEN sbq.submission_id = camdecmpsaux.get_last_submission_list(sbs.mon_plan_id,sbq.rpt_period_id,sbq.process_cd) 
+                WHEN sbq.submission_id = camdecmps.get_last_submission_list(sbs.mon_plan_id,sbq.rpt_period_id,sbq.process_cd)
```
Comment (mark-hayward-erg) [inline camdecmps/views/vw_submission_list.sql]: needs to call "get_last_submission".

File: deployments/ecmps/release-v2.0-fix/Sprint19/6622/camdecmps/functions/get_last_submission.sql [hunk 3]
```diff
@@ -0,0 +1,27 @@
+CREATE OR REPLACE FUNCTION camdecmps.get_last_submission_list(
```
Comment (mark-hayward-erg) [inline deployments/ecmps/release-v2.0-fix/Sprint19/6622/camdecmps/functions/get_last_submission.sql]: The actual name of the function needs to be "get_last_submission".  The file name is correct.

File: deployments/ecmps/release-v2.0-fix/Sprint19/6622/camdecmps/views/vw_submission_list.sql [hunk 4]
```diff
@@ -0,0 +1,94 @@
...
+               by  frq.end_rpt_period_id desc
+            limit  1
+       ) as reporting_frequency,
+       sbq.process_cd,
+       sbq.submission_id,
+       sbq.queued_time,
+       sev.severity_cd_description as severity_level,
+        (SELECT
+                CASE 
+                WHEN sbq.submission_id = camdecmps.get_last_submission_list(sbs.mon_plan_id,sbq.rpt_period_id,sbq.process_cd)
```
Comment (mark-hayward-erg) [inline deployments/ecmps/release-v2.0-fix/Sprint19/6622/camdecmps/views/vw_submission_list.sql]: needs to call "get_last_submission".

**Review by mark-hayward-erg — CHANGES_REQUESTED** [review]

**Review by mark-hayward-erg — CHANGES_REQUESTED** [review]
@Jhernandez29  Thinking about this some more, I think that both the function and the view should live in the camdecmpsaux schema (and be under the relevant camdecmpsaux folders in the repo).

The data involved is primarily data from camdecmpsaux tables (particularly the main submission tables).

File: camdecmps/functions/get_last_submission.sql (hunk 1 above)
Comment (Jhernandez29) [reply camdecmps/functions/get_last_submission.sql]: corrected name with commit https://github.com/US-EPA-CAMD/easey-db-scripts/pull/128/commits/5583eea29d931d9c2817400ae2275de007c1fb4f

File: camdecmps/views/vw_submission_list.sql (hunk 2 above)
Comment (Jhernandez29) [reply camdecmps/views/vw_submission_list.sql]: corrected name with commit https://github.com/US-EPA-CAMD/easey-db-scripts/pull/128/commits/5583eea29d931d9c2817400ae2275de007c1fb4f

File: deployments/ecmps/release-v2.0-fix/Sprint19/6622/camdecmps/functions/get_last_submission.sql (hunk 3 above)
Comment (Jhernandez29) [reply deployments/ecmps/release-v2.0-fix/Sprint19/6622/camdecmps/functions/get_last_submission.sql]: corrected name with commit https://github.com/US-EPA-CAMD/easey-db-scripts/pull/128/commits/5583eea29d931d9c2817400ae2275de007c1fb4f

File: deployments/ecmps/release-v2.0-fix/Sprint19/6622/camdecmps/views/vw_submission_list.sql (hunk 4 above)
Comment (Jhernandez29) [reply deployments/ecmps/release-v2.0-fix/Sprint19/6622/camdecmps/views/vw_submission_list.sql]: corrected name with commit https://github.com/US-EPA-CAMD/easey-db-scripts/pull/128/commits/5583eea29d931d9c2817400ae2275de007c1fb4f

**Review by mark-hayward-erg — APPROVED** [review]
