### PR TITLE
fix/#6073 Last Submission ID Related Issue on EM Submission Access

### LINKED ISSUE #6073: Maintain EM Submission Access: Last Submission ID
In System Administration - Emission Submission Access - Maintain EM Submission Access, the Last Submission ID value does not change when resubmissions are made. Also, when resubmission windows are opened, the open window record is pre-populated with the original submission ID.

Note that it looks like new submission ID records are NOT being created for resubmissions- the original submission ID is being reused (developer should re-verify this). Example:

There are 3 submission windows for ORIS Code 3, CS0AAN, 1, 2 for 2023q3-- 2 windows have submissions received and one does not. The following query shows all 3 windows have the same submission ID.
`select * from camdecmpsaux.vw_em_submission_access where rpt_period_id = 123 and mon_plan_id = 'TWCORNEL5-C0E3879920A14159BAA98E03F1980A7A' order by access_begin_date ; `

## Acceptance Tests
1. Each submission (including resubmissions) should have a distinct submission_ID, severity_cd, and severity_cd_description. 
2. When resubmission windows are opened, the submission ID, severity_cd, and severity_cd_description values should all be null since there has not yet been a submission for that window.
3. When a file is resubmitted, the submission ID, severity_cd, and severity_cd_description values for the resubmission should be recorded in the database and shown on the screen.

### PR DESCRIPTION
**Pull request by EvanSun220**
### **Related ticket:**

- ticket [#6073](https://github.com/orgs/US-EPA-CAMD/projects/2/views/51?filterQuery=&sliceBy%5Bvalue%5D=EvanSun220&pane=issue&itemId=53268924&issue=US-EPA-CAMD%7Ceasey-ui%7C6073)

### **Updates:**

- Updated **_camdecmpsaux.get_last_submission_in_window_** function to get the last submission id for a specific record.
- Updated the way to retrieve submission_id for view **_vw_em_submission_access_** by using the updated function get_last_submission_in_window.

### **Notes:** 
02/19/2025
- Import Historical Emissions Data & Evaluate module is not working at this moment, will need to fix those first before testing the new changes.

02/19/2025
- Key functions restored. New changes passed the test.

### CODE REVIEW

File: camdecmpsaux/functions/get_submission_in_window.sql [hunk 1]
```diff
@@ -0,0 +1,33 @@
...
+    v_submission_id := null;
+	
+	SELECT SQ.submission_id
+	INTO v_submission_id
+	FROM camdecmpsaux.submission_set SS
+	JOIN camdecmpsaux.submission_queue SQ USING(submission_set_id)
+	WHERE SS.mon_plan_id = v_mon_plan_id
+		AND SQ.rpt_period_id = v_rpt_period_id
+		AND SQ.process_cd = 'EM'
+		AND DATE(SQ.queued_time) = DATE(v_begin_date)
```
Comment (djw4erg) [inline camdecmpsaux/functions/get_submission_in_window.sql]: ## Requested Change

- This function should look for submissions queued between v_begin_date and v_end_date, not just on v_begin_date .

## Potential Additional Change

- The original ECMPS 1.0 function accounts for the potentially overlapping emission window date ranges for a mon_plan_id/rpt_period_id combination.  The function treats a submission that also occurred in another submission window that started later as belonging to the later window, not the one for which the function was called.
  -  This ECMPS 2.0 version does not perform the check for subsequent windows to which submissions actually belong.
  - Need to ensure this check is not needed.

### ECMPS 1.0 Version (Oracle)

```
FUNCTION FNCGETLASTSUBMISSIONINWINDOW
(
    INMONPLANID   EM_SUBMISSION_ACCESS.MON_PLAN_ID%TYPE,
    INRPTPERIODID EM_SUBMISSION_ACCESS.RPT_PERIOD_ID%TYPE,
    INBEGINDATE   EM_SUBMISSION_ACCESS.ACCESS_BEGIN_DATE%TYPE,
    INENDDATE     EM_SUBMISSION_ACCESS.ACCESS_END_DATE%TYPE
)
    RETURN SUBMISSION_LOG.SUBMISSION_ID%TYPE
IS
    V_SUBMISSION_ID SUBMISSION_LOG.SUBMISSION_ID%TYPE;
BEGIN
    
    V_SUBMISSION_ID := NULL;

    SELECT  SL2.SUBMISSION_ID
      INTO  V_SUBMISSION_ID
      FROM  SUBMISSION_LOG SL2,
            (
                SELECT  SL.MON_PLAN_ID,
                        SL.RPT_PERIOD_ID,
                        MAX( SL.ADD_DATE ) AS ADD_DATE
                  FROM  SUBMISSION_LOG SL,
                        (
                            SELECT  MON_PLAN_ID,
                                    MIN
                                    (
                                        CASE
                                            WHEN ACCESS_BEGIN_DATE > ADD_DATE THEN
                                                ACCESS_BEGIN_DATE
                                            ELSE
                                                ADD_DATE
                                        END
                                    ) AS ACCESS_BEGIN_DATE
                              FROM  EM_SUBMISSION_ACCESS
                             WHERE  MON_PLAN_ID = INMONPLANID
                               AND  RPT_PERIOD_ID = INRPTPERIODID
                               AND  ACCESS_BEGIN_DATE > INBEGINDATE
                             GROUP
                                BY  MON_PLAN_ID
                        ) ESA
                 WHERE  FILE_TYPE_CD = 'EM'
                   AND  SL.MON_PLAN_ID = INMONPLANID
                   AND  SL.RPT_PERIOD_ID = INRPTPERIODID
                   AND  TRUNC( SL.ADD_DATE ) >= TRUNC( INBEGINDATE )
                   AND  TRUNC( SL.ADD_DATE ) <= TRUNC( INENDDATE )
                   AND  SL.MON_PLAN_ID = ESA.MON_PLAN_ID(+)
                   AND  ( ESA.MON_PLAN_ID IS NULL OR SL.ADD_DATE < ESA.ACCESS_BEGIN_DATE )
                 GROUP
                    BY  SL.MON_PLAN_ID, 
                        SL.RPT_PERIOD_ID
            ) MAXSUB
     WHERE  SL2.MON_PLAN_ID = MAXSUB.MON_PLAN_ID
       AND  SL2.RPT_PERIOD_ID = MAXSUB.RPT_PERIOD_ID
       AND  SL2.ADD_DATE = MAXSUB.ADD_DATE
       AND  SL2.MON_PLAN_ID = INMONPLANID
       AND  SL2.FILE_TYPE_CD = 'EM'
       AND  SL2.RPT_PERIOD_ID = INRPTPERIODID;

    RETURN V_SUBMISSION_ID;

END FNCGETLASTSUBMISSIONINWINDOW;
```

**Review by djw4erg — CHANGES_REQUESTED** [review]

File: camdecmpsaux/functions/get_last_submission_in_window.sql [hunk 2]
```diff
@@ -3,34 +3,72 @@
...
+            WHERE mon_plan_id = v_mon_plan_id
+              AND rpt_period_id = v_rpt_period_id
+              AND access_begin_date > v_begin_date
+            GROUP BY mon_plan_id
+        ) ESA 
+        ON SL.mon_plan_id = ESA.mon_plan_id
+        WHERE SL.process_cd = 'EM'
+          AND SL.mon_plan_id = v_mon_plan_id
+          AND SL.rpt_period_id = v_rpt_period_id
+          AND SL.queued_time BETWEEN v_begin_date AND v_end_date
```
Comment (djw4erg) [inline camdecmpsaux/functions/get_last_submission_in_window.sql]: ## The Change

Need to strip the time from SL.queued_time before comparing to v_end_date, other submission that were queued on the date for v_end_date will be excluded unless they were queued exactly at midnight.

### The following set of arguments demonstrates the problem:

- **v_mon_plan_id**: MDC-A386218BD0334270BDB2FBB2192D1C0A
- **v_rpt_period_id**: 123
- **v_begin_date**: 2024-09-30
- **v_end_date**: 2024-09-30

## Potential Simpler SQL

I wish that I had skipped the Oracle version as an example.  It is hard to read.  As long as we are making a change, I would **suggest** using something like the following example.  **This is Just a suggestion!**

### Potential Replacement Version:
```
select  sbq.submission_id
  into  v_submission_id
  from  (
            select  v_mon_plan_id as mon_plan_id,
                    v_rpt_period_id as rpt_period_id,
                    v_begin_date as access_begin_date,
                    v_end_date as access_end_date
        ) esa
        left join camdecmpsaux.SUBMISSION_SET sbs using ( mon_plan_id )
        left join camdecmpsaux.SUBMISSION_QUEUE sbq using ( submission_set_id )
 where  sbq.process_cd = 'EM'
   and  sbq.rpt_period_id = esa.rpt_period_id 
   and  sbq.queued_time::date between esa.access_begin_date and esa.access_end_date 
   -- Ensure that the submission does not belong to a later window.
   and  not exists
        (
            select  1
              from  camdecmpsaux.EM_SUBMISSION_ACCESS exs
             where  exs.mon_plan_id = esa.mon_plan_id 
               and  exs.rpt_period_id = esa.rpt_period_id 
               -- Only check windows where the later of the begin and add dates is after the target window begin date.
               and  greatest( exs.access_begin_date, exs.add_date::date ) > esa.access_begin_date
               -- Ensure that the later of the begin and add times is on or before the queued time of the submission.
               and  greatest( exs.access_begin_date::timestamp, exs.add_date ) <= sbq.queued_time
        )
 order
    by  sbq.queued_time desc
 limit  1;
```


### Working Version:
```
select  esa.em_sub_access_id,
        esa.mon_plan_id,
        esa.rpt_period_id,
        esa.access_begin_date,
        esa.access_end_date,
        sbq.queued_time,
        sbq.submission_id
  from  camdecmpsaux.EM_SUBMISSION_ACCESS esa
        left join camdecmpsaux.SUBMISSION_SET sbs using ( mon_plan_id )
        left join camdecmpsaux.SUBMISSION_QUEUE sbq using ( submission_set_id )
 where  esa.em_sub_access_id = 369335
   and  sbq.process_cd = 'EM'
   and  sbq.rpt_period_id = esa.rpt_period_id 
   and  sbq.queued_time::date between esa.access_begin_date and esa.access_end_date 
   -- Ensure that the submission does not belong to a later window.
   and  not exists
        (
            select  1
              from  camdecmpsaux.EM_SUBMISSION_ACCESS exs
             where  exs.mon_plan_id = esa.mon_plan_id 
               and  exs.rpt_period_id = esa.rpt_period_id 
               -- Only check windows where the later of the begin and add dates is after the target window begin date.
               and  greatest( exs.access_begin_date, exs.add_date::date ) > esa.access_begin_date
               -- Ensure that the later of the begin and add times is on or before the queued time of the submission.
               and  greatest( exs.access_begin_date::timestamp, exs.add_date ) <= sbq.queued_time
        )
 order
    by  sbq.queued_time desc
 limit  1;
```

**Review by djw4erg — CHANGES_REQUESTED** [review]

**Review by djw4erg — APPROVED** [review]

**Review by djw4erg — CHANGES_REQUESTED** [review]
Evan, the version of the function on Dev was not updated.  The change itself looks good.

**Review by djw4erg — APPROVED** [review]
