### PR TITLE
Fixed #6934

### LINKED ISSUE #6934: Initial/ Resubmission Windows not Extending
During testing of #6610 and #6739, discovered that initial submission windows and resubmission windows are not extending when a file has not yet been submitted. These windows should be extended an additional 30 days until a file is submitted.

Steps to reproduce:

1. Open a resubmission window in the Emission Submission Access admin tool or call camdecmpsaux.init_and_close_em_submission_access in the database to open an initial submission window for a quarter
2. Change the camdecmpsaux.em_submission_access.access_end_date for the window in the database to yesterday
3. Run the following query on dev to run the SubmissionWindowManagement job
UPDATE camdaux.job_configuration jc
SET run_once = true
WHERE jc.job_class = 'SubmissionWindowManagement';
4. The window is closed

### PR DESCRIPTION
**Pull request by yonatan-dp**
Fixed an issue where initial submission windows and resubmission windows are not extending when a file has not yet been submitted. These windows are now extended an additional 30 days until a file is submitted.

### CODE REVIEW

File: camdecmpsaux/views/vw_submission_window_job_close.sql [hunk 1]
```diff
@@ -32,8 +32,10 @@ select
 		else 'F'
 	end as CHECK_FOR_REMINDER,
 	case
+        when S.SUBMISSION_ID IS NULL THEN 'T' --Also, extend the window if there are no submissions
 		when S.STATUS_CD IN ('NOLOAD') OR
-             S.SEVERITY_CD = 'CRIT1' OR S.SEVERITY_CD = 'CRIT2' then 'T'
```
Comment (djw4erg) [inline camdecmpsaux/views/vw_submission_window_job_close.sql:36]: Was the problem with windows not being extended limited to CRIT2 submissions?  This change would indicate that was the only problem, but #6934 does not say that in its Description or in a subsequent comment.

File: camdecmpsaux/procedures/init_and_close_em_submission_access.sql
Comment (djw4erg) [inline camdecmpsaux/procedures/init_and_close_em_submission_access.sql:1]: Just for my information, was the type issue causing problems or is this just making the type needed explicit.

File: camdecmpsaux/views/vw_submission_window_job_close.sql (hunk 1 above)
Comment (yonatan-dp) [reply camdecmpsaux/views/vw_submission_window_job_close.sql:36]: If I understand your comment correctly, no, the issue is not with CRIT2 submission. If you are looking the change from line 36 to line 37, that change is just to simplify the SQL, not a logical change. The change to satisfy #6934 is on line 35.

File: camdecmpsaux/procedures/init_and_close_em_submission_access.sql
Comment (yonatan-dp) [reply camdecmpsaux/procedures/init_and_close_em_submission_access.sql:1]: Yes, it was causing an issue during my testing.

Comment (djw4erg) [reply camdecmpsaux/procedures/init_and_close_em_submission_access.sql:1]: Thanks!

File: camdecmpsaux/views/vw_submission_window_job_close.sql (hunk 1 above)
Comment (djw4erg) [reply camdecmpsaux/views/vw_submission_window_job_close.sql:36]: Ugh!  Bad reviewing.  I kept seeing that SEVEIRY_CD as something else.  Multiple times!  Thanks Yonatan.

**Review by djw4erg — DISMISSED** [review]

**Review by mark-hayward-erg — APPROVED** [review]
